steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          echo "Step: Terraform Init"
          terraform init
  - id: 'terraform apply'
    name: 'hashicorp/terraform:137'
    entrypoint: 'sh'
    args:
      - -c
      - |
          echo "[APPLY] Installing Python3 and requirements."
          apk add --no-cache python3 py3-pip
          pip install -r .terraform/modules/aviatrix-controller-gcp/requirements.txt
          echo "[APPLY] Running Terraform apply."
          terraform apply
    env:
      - 'TF_VAR_project=$PROJECT_ID'
      - 'TF_VAR_zone=us-central1-c'
      - 'TF_VAR_controller_name=cloudbuild-controller'
      - 'TF_VAR_image=aviatrix-public/avx-controller-gcp-2022-10-31'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-email/versions/1
      env: 'TF_VAR_aviatrix_controller_admin_email'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-password/versions/1
      env: 'TF_VAR_aviatrix_controller_admin_password'
    - versionName: projects/$PROJECT_ID/secrets/avx-customer-id/versions/1
      env: 'TF_VAR_aviatrix_customer_id'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-cidrs/versions/1
      env: 'TF_VAR_incoming_ssl_cidrs'