steps:
  - id: 'controller-network'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args: ['./run-terraform.sh', 'controller-network']
    env:
      - 'TF_VAR_controller_name=mattk-controller'
      - 'TF_VAR_image=aviatrix-public/avx-controller-gcp-2022-10-31'
  - id: 'controller-instance'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args: ['./run-terraform.sh', 'controller-instance']
    env:
      - 'TF_VAR_controller_name=mattk-controller'
      - 'TF_VAR_image=aviatrix-public/avx-controller-gcp-2022-10-31'
    secretEnv:
      - 'TF_VAR_admin_cidrs'
  - id: 'controller-firewall'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args: ['./run-terraform.sh', 'controller-firewall']
  - id: 'controller-init-py'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args: ['./run-init-py.sh']
    secretEnv:
    - 'AVIATRIX_CUSTOMER_ID'
    - 'AVIATRIX_CONTROLLER_ADMIN_EMAIL'
  - id: 'controller-init-tf'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args: ['./run-terraform.sh', 'controller-init-tf']
  - id: 'controller-firewall-destroy'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args: ['./run-terraform.sh', 'controller-firewall', 'destroy']
options:
  env:
    - 'TF_VAR_project=$PROJECT_ID'
    - 'AVIATRIX_USERNAME=admin'
  secretEnv:
    - 'TF_VAR_state_bucket'
    - 'TF_VAR_subnetwork_self_link'
    - 'AVIATRIX_PASSWORD'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-email/versions/latest
      env: 'AVIATRIX_CONTROLLER_ADMIN_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-password/versions/latest
      env: 'AVIATRIX_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/avx-customer-id/versions/latest
      env: 'AVIATRIX_CUSTOMER_ID'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-cidrs/versions/latest
      env: 'TF_VAR_admin_cidrs'
    - versionName: projects/$PROJECT_ID/secrets/avx-state-bucket/versions/latest
      env: 'TF_VAR_state_bucket'
    - versionName: projects/$PROJECT_ID/secrets/avx-subnetwork/versions/latest
      env: 'TF_VAR_subnetwork_self_link'