steps:
  - id: 'controller'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd controller
          echo "[CONTROLLER]: Terraform Init"
          terraform init
          echo "[CONTROLLER] Installing Python3 and requirements."
          apk add --no-cache python3 py3-pip curl
          pip install -r .terraform/modules/aviatrix-controller-gcp/requirements.txt
          export TF_VAR_myip=$(curl -s ifconfig.me)
          echo "[CONTROLLER] My build worker IP is ${TF_VAR_myip}"
          echo "[CONTROLLER] Running Terraform apply."
          terraform apply -auto-approve -lock=false
    env:
      - 'TF_VAR_project=$PROJECT_ID'
      - 'TF_VAR_zone=us-central1-c'
      - 'TF_VAR_controller_name=cloudbuild-controller'
      - 'TF_VAR_image=aviatrix-public/avx-controller-gcp-2022-10-31'
      - 'TF_VAR_subnet_cidr=10.31.0.0/24'
      - 'TF_VAR_network_name=aviatrix-controller-network'
    secretEnv:
      - 'TF_VAR_aviatrix_controller_admin_email'
      - 'TF_VAR_aviatrix_controller_admin_password'
      - 'TF_VAR_aviatrix_customer_id'
      - 'TF_VAR_incoming_ssl_cidrs'
  - id: 'gateways'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd gateways
          echo "[GATEWAYS]: Terraform Init"
          terraform init
          apk add --no-cache curl
          export TF_VAR_myip=$(curl -s ifconfig.me)
          echo "[GATEWAYS] My build worker IP is ${TF_VAR_myip}"
          echo "[GATEWAYS] Running Terraform apply."
          terraform apply -auto-approve -lock=false
    env:
      - 'TF_VAR_project=$PROJECT_ID'
      - 'TF_VAR_network_name=aviatrix-controller-network'
    secretEnv:
      - 'TF_VAR_aviatrix_controller_admin_password'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-email/versions/1
      env: 'TF_VAR_aviatrix_controller_admin_email'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-password/versions/1
      env: 'TF_VAR_aviatrix_controller_admin_password'
    - versionName: projects/$PROJECT_ID/secrets/avx-customer-id/versions/1
      env: 'TF_VAR_aviatrix_customer_id'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-cidrs/versions/1
      env: 'TF_VAR_incoming_ssl_cidrs'