steps:
  - id: 'controller-network'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd controller-network
          echo "[CONTROLLER-NETWORK]: Running Terraform Init"
          terraform init -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/init-tf" -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/network"
          echo "[CONTROLLER-NETWORK] Running Terraform apply."
          terraform apply -auto-approve -lock=false
    env:
      - 'TF_VAR_controller_name=mattk-controller'
      - 'TF_VAR_image=aviatrix-public/avx-controller-gcp-2022-10-31'
  - id: 'controller-instance'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd controller-instance
          echo "[CONTROLLER-INSTANCE]: Running Terraform Init"
          terraform init -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/init-tf" -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/instance"
          echo "[CONTROLLER-INSTANCE]: Running Terraform apply."
          terraform apply -auto-approve -lock=false
    env:
      - 'TF_VAR_controller_name=mattk-controller'
      - 'TF_VAR_image=aviatrix-public/avx-controller-gcp-2022-10-31'
    secretEnv:
      - 'TF_VAR_admin_cidrs'
  - id: 'controller-firewall'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd controller-firewall
          echo "[CONTROLLER-FIREWALL]: Adding Cloud Build Worker IP to firewall."
          echo "[CONTROLLER-FIREWALL]: Running Terraform Init"
          terraform init -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/init-tf"
          echo "[CONTROLLER-FIREWALL]: Running Terraform apply."
          terraform apply -auto-approve -lock=false
          echo "[CONTROLLER-FIREWALL]: Added worker IP to firewall."
  - id: 'controller-init-py'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          echo "[CONTROLLER-INIT-PY]: Set environment variables."
          export AVIATRIX_PRIVATE_IP=$(cat controller_private_ip)
          export AVIATRIX_CONTROLLER_IP=$(cat controller_public_ip)
          echo "[CONTROLLER-INIT-PY]: Installing Python3 and requirements."
          apk add --no-cache python3 py3-pip
          pip install requests
          cd controller-init-py
          echo "[CONTROLLER-INIT-PY]: Running init script."
          python3 init.py
    secretEnv:
    - 'AVIATRIX_CUSTOMER_ID'
    - 'AVIATRIX_CONTROLLER_ADMIN_EMAIL'
  - id: 'controller-init-tf'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd controller-init-tf
          echo "[CONTROLLER-INIT-TF]: Running Terraform Init."
          terraform init -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/init-tf"
          echo "[CONTROLLER-INIT-TF]: Running Terraform Apply."
          terraform apply -auto-approve -lock=false
  - id: 'controller-firewall-destroy'
    name: 'hashicorp/terraform:1.3.7'
    entrypoint: 'sh'
    args:
      - -c
      - |
          cd controller-firewall
          echo "[CONTROLLER-FIREWALL]: Removing Cloud Build Worker IP from firewall."
          echo "[CONTROLLER-FIREWALL]: Running Terraform Init"
          terraform init -backend-config="bucket=$(echo state_bucket)" -backend-config="prefix=avx/init-tf"
          echo "[CONTROLLER-FIREWALL]: Running Terraform apply."
          terraform destroy -auto-approve -lock=false
          echo "[CONTROLLER-FIREWALL]: Removed worker IP from firewall."
options:
  env:
    - 'TF_VAR_project=$PROJECT_ID'
  secretEnv:
    - 'state_bucket'
    - 'TF_VAR_subnetwork_self_link'
    - 'AVIATRIX_PASSWORD'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-email/versions/1
      env: 'AVIATRIX_CONTROLLER_ADMIN_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-password/versions/1
      env: 'AVIATRIX_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/avx-customer-id/versions/1
      env: 'AVIATRIX_CUSTOMER_ID'
    - versionName: projects/$PROJECT_ID/secrets/avx-admin-cidrs/versions/1
      env: 'TF_VAR_admin_cidrs'
    - versionName: projects/$PROJECT_ID/secrets/avx-state-bucket/versions/1
      env: 'state_bucket'
    - versionName: projects/$PROJECT_ID/secrets/avx-subnetwork/versions/1
      env: 'TF_VAR_subnetwork_self_link'